-- Generated by tools/semantic_compiler/build.py; do not edit by hand.
-- Dialogue responses shard 01; keep this file data-only.
return {
    {
            ["id"] = "semantic.accept",
            ["variants"] = {
                {
                    ["fallback"] = "Okay, I'll get started.",
                    ["id"] = "semantic.accept.dataset.pending_started",
                    ["priority"] = 1,
                    ["templateID"] = "semantic.accept.dataset.pending_started",
                    ["when"] = {
                        ["hasPendingRequest"] = true,
                    },
                },
                {
                    ["fallback"] = "All right. I can take care of that.",
                    ["id"] = "semantic.accept.dataset.pending_care",
                    ["priority"] = 1,
                    ["templateID"] = "semantic.accept.dataset.pending_care",
                    ["when"] = {
                        ["hasPendingRequest"] = true,
                    },
                },
            },
        },
    {
            ["id"] = "semantic.compliment",
            ["variants"] = {
                {
                    ["fallback"] = "That's kind of you. I appreciate it.",
                    ["id"] = "semantic.compliment.dataset.kind_of_you",
                    ["templateID"] = "semantic.compliment.dataset.kind_of_you",
                },
                {
                    ["fallback"] = "Aw, thank you. That means a lot.",
                    ["id"] = "semantic.compliment.dataset.means_a_lot",
                    ["templateID"] = "semantic.compliment.dataset.means_a_lot",
                },
            },
        },
    {
            ["id"] = "semantic.greeting",
            ["variants"] = {
                {
                    ["fallback"] = "Hey. How are you holding up?",
                    ["id"] = "semantic.greeting.dataset.holding_up",
                    ["templateID"] = "semantic.greeting.dataset.holding_up",
                },
                {
                    ["fallback"] = "Good to see you again.",
                    ["id"] = "semantic.greeting.dataset.good_to_see",
                    ["templateID"] = "semantic.greeting.dataset.good_to_see",
                },
                {
                    ["fallback"] = "Hey. How are things going?",
                    ["id"] = "semantic.greeting.dataset.how_things",
                    ["templateID"] = "semantic.greeting.dataset.how_things",
                },
            },
        },
    {
            ["id"] = "semantic.offer",
            ["variants"] = {
                {
                    ["fallback"] = "That would help a lot. Could I have some?",
                    ["id"] = "semantic.offer.dataset.hungry_share",
                    ["priority"] = 2,
                    ["templateID"] = "semantic.offer.dataset.hungry_share",
                    ["when"] = {
                        ["needType"] = "hunger",
                        ["needUrgency"] = {
                            "moderate",
                            "severe",
                            "emergency",
                            "critical",
                        },
                    },
                },
                {
                    ["fallback"] = "I'd appreciate a bite. Would you share?",
                    ["id"] = "semantic.offer.dataset.hungry_appreciate",
                    ["priority"] = 2,
                    ["templateID"] = "semantic.offer.dataset.hungry_appreciate",
                    ["when"] = {
                        ["needType"] = "hunger",
                        ["needUrgency"] = {
                            "moderate",
                            "severe",
                            "emergency",
                            "critical",
                        },
                    },
                },
            },
        },
    {
            ["id"] = "semantic.question.activity",
            ["variants"] = {
                {
                    ["fallback"] = "Just doing what I can to keep things moving.",
                    ["id"] = "semantic.question.activity.dataset.keep_moving",
                    ["templateID"] = "semantic.question.activity.dataset.keep_moving",
                },
                {
                    ["fallback"] = "A little bit of everything.",
                    ["id"] = "semantic.question.activity.dataset.bit_of_everything",
                    ["templateID"] = "semantic.question.activity.dataset.bit_of_everything",
                },
                {
                    ["fallback"] = "Just taking care of what needs doing.",
                    ["id"] = "semantic.question.activity.dataset.taking_care",
                    ["templateID"] = "semantic.question.activity.dataset.taking_care",
                },
            },
        },
    {
            ["id"] = "semantic.question.identity",
            ["variants"] = {
                {
                    ["fallback"] = "I keep my name to myself until I know someone better. What should I call you?",
                    ["id"] = "semantic.question.identity.dataset.stranger_alt_1",
                    ["templateID"] = "semantic.question.identity.stranger_alt_1",
                },
                {
                    ["fallback"] = "Let's get to know each other first. What do people call you?",
                    ["id"] = "semantic.question.identity.dataset.stranger_alt_2",
                    ["templateID"] = "semantic.question.identity.stranger_alt_2",
                },
                {
                    ["fallback"] = "I don't trust you enough to share my name. Who are you, really?",
                    ["id"] = "semantic.question.identity.dataset.wary_alt_1",
                    ["priority"] = 2,
                    ["templateID"] = "semantic.question.identity.wary_alt_1",
                    ["when"] = {
                        ["identityTrust"] = "untrustworthy",
                    },
                },
                {
                    ["fallback"] = "After that lie, I'm not telling you my name. Tell me the truth about yours.",
                    ["id"] = "semantic.question.identity.dataset.wary_alt_2",
                    ["priority"] = 2,
                    ["templateID"] = "semantic.question.identity.wary_alt_2",
                    ["when"] = {
                        ["identityTrust"] = "untrustworthy",
                    },
                },
            },
        },
    {
            ["id"] = "semantic.question.wellbeing",
            ["variants"] = {
                {
                    ["fallback"] = "I'm hanging in there. Thanks for asking.",
                    ["id"] = "semantic.question.wellbeing.dataset.hanging_in",
                    ["templateID"] = "semantic.question.wellbeing.dataset.hanging_in",
                },
                {
                    ["fallback"] = "Doing okay, all things considered.",
                    ["id"] = "semantic.question.wellbeing.dataset.all_things_considered",
                    ["templateID"] = "semantic.question.wellbeing.dataset.all_things_considered",
                },
                {
                    ["fallback"] = "I'm getting by, one day at a time. How about you?",
                    ["id"] = "semantic.question.wellbeing.dataset.getting_by",
                    ["templateID"] = "semantic.question.wellbeing.dataset.getting_by",
                },
                {
                    ["fallback"] = "I'm hungry, but I'll manage. If you have food to spare, I'd appreciate it.",
                    ["id"] = "semantic.question.wellbeing.dataset.hungry",
                    ["priority"] = 2,
                    ["templateID"] = "semantic.question.wellbeing.dataset.hungry",
                    ["when"] = {
                        ["needType"] = "hunger",
                        ["needUrgency"] = {
                            "moderate",
                            "severe",
                            "emergency",
                            "critical",
                        },
                    },
                },
                {
                    ["fallback"] = "I'm pretty thirsty. If you have water, could you spare some?",
                    ["id"] = "semantic.question.wellbeing.dataset.thirsty",
                    ["priority"] = 3,
                    ["templateID"] = "semantic.question.wellbeing.dataset.thirsty",
                    ["when"] = {
                        ["needType"] = "thirst",
                        ["needUrgency"] = {
                            "moderate",
                            "severe",
                            "emergency",
                            "critical",
                        },
                    },
                },
                {
                    ["fallback"] = "I'm tired, though I can manage for now.",
                    ["id"] = "semantic.question.wellbeing.dataset.tired",
                    ["priority"] = 2,
                    ["templateID"] = "semantic.question.wellbeing.dataset.tired",
                    ["when"] = {
                        ["needType"] = "fatigue",
                        ["needUrgency"] = {
                            "moderate",
                            "severe",
                            "emergency",
                            "critical",
                        },
                    },
                },
            },
        },
    {
            ["id"] = "semantic.refuse",
            ["variants"] = {
                {
                    ["fallback"] = "I can't take that on right now.",
                    ["id"] = "semantic.refuse.dataset.pending_unavailable",
                    ["priority"] = 1,
                    ["templateID"] = "semantic.refuse.dataset.pending_unavailable",
                    ["when"] = {
                        ["hasPendingRequest"] = true,
                    },
                },
                {
                    ["fallback"] = "Not this time. I have enough to manage.",
                    ["id"] = "semantic.refuse.dataset.pending_enough",
                    ["priority"] = 1,
                    ["templateID"] = "semantic.refuse.dataset.pending_enough",
                    ["when"] = {
                        ["hasPendingRequest"] = true,
                    },
                },
            },
        },
    {
            ["id"] = "semantic.thanks",
            ["variants"] = {
                {
                    ["fallback"] = "No problem at all.",
                    ["id"] = "semantic.thanks.dataset.no_problem",
                    ["templateID"] = "semantic.thanks.dataset.no_problem",
                },
                {
                    ["fallback"] = "Anytime.",
                    ["id"] = "semantic.thanks.dataset.anytime",
                    ["templateID"] = "semantic.thanks.dataset.anytime",
                },
                {
                    ["fallback"] = "Glad I could help.",
                    ["id"] = "semantic.thanks.dataset.glady",
                    ["templateID"] = "semantic.thanks.dataset.glady",
                },
            },
        },
}
