-- Generated by tools/semantic_compiler/build.py; do not edit by hand.
-- Stable entry point for deterministic dialogue data shards.
local result = {
    ["source"] = {
        ["contentLicense"] = "Project Hoomans authored content",
        ["name"] = "Project Hoomans Common Interaction Seed",
        ["references"] = {
            {
                ["name"] = "DailyDialog",
                ["url"] = "https://aclanthology.org/I17-1099/",
                ["use"] = "Everyday dialogue-act coverage guidance; no corpus turns are copied.",
            },
            {
                ["name"] = "EmpatheticDialogues",
                ["url"] = "https://github.com/facebookresearch/EmpatheticDialogues",
                ["use"] = "Emotion-aware interaction coverage guidance; no corpus turns are copied.",
            },
        },
        ["version"] = "1",
    },
    ["patterns"] = {},
    ["responsePools"] = {},
}
local function append(target, shard)
    for index = 1, #shard do
        target[#target + 1] = shard[index]
    end
end
append(result["patterns"], require "PNC/Semantics/PNC_SemanticGeneratedDialogue_Patterns_01")
append(result["patterns"], require "PNC/Semantics/PNC_SemanticGeneratedDialogue_Patterns_02")
append(result["responsePools"], require "PNC/Semantics/PNC_SemanticGeneratedDialogue_Responses_01")
return result
