-- Generated by tools/semantic_compiler/build.py; do not edit by hand.
-- Exact Hoomans-authored interaction patterns and response variants.
-- Referenced dialogue corpora provide coverage labels only; no turns are copied.
return {
    ["patterns"] = {
        {
            ["confidence"] = 0.97,
            ["emit"] = {
                ["intent"] = "GREET",
                ["speechAct"] = "GREET",
            },
            ["id"] = "pnc.dataset.greeting.glad_to_see_you_again",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "glad",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "to",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "see",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "again",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "GREET",
                ["speechAct"] = "GREET",
            },
            ["id"] = "pnc.dataset.greeting.good_to_see_you_again",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "good",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "to",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "see",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "again",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "GREET",
                ["speechAct"] = "GREET",
            },
            ["id"] = "pnc.dataset.greeting.long_time_no_see",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "long",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "time",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "no",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "see",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "GREET",
                ["speechAct"] = "GREET",
            },
            ["id"] = "pnc.dataset.greeting.nice_to_see_you_again",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "nice",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "to",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "see",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "again",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.97,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "ACTIVITY",
            },
            ["id"] = "pnc.dataset.question.activity.what_are_you_focused_on",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "are",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "focused",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "on",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "ACTIVITY",
            },
            ["id"] = "pnc.dataset.question.activity.what_are_you_working_on",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "are",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "working",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "on",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "ACTIVITY",
            },
            ["id"] = "pnc.dataset.question.activity.what_have_you_been_doing_today",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "have",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "been",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "doing",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "today",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "ACTIVITY",
            },
            ["id"] = "pnc.dataset.question.activity.what_have_you_been_up_to_lately",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "have",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "been",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "up",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "to",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "lately",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.can_i_ask_your_name",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "can",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "i",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "ask",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "your",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "name",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.can_you_tell_me_your_name",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "can",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "tell",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "me",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "your",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "name",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.may_i_ask_your_name",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "may",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "i",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "ask",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "your",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "name",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.may_i_know_your_name",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "may",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "i",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "know",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "your",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "name",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.mind_telling_me_your_name",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "mind",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "telling",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "me",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "your",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "name",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.what_do_people_call_you",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "do",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "people",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "call",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.what_do_you_go_by",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "do",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "go",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "by",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.what_should_i_call_you",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "should",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "i",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "call",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.who_am_i_speaking_with",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "who",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "am",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "i",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "speaking",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "with",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.who_am_i_talking_to",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "who",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "am",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "i",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "talking",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "to",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.are_you_holding_up_okay",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "are",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "holding",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "up",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "okay",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.how_are_things_going",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "how",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "are",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "things",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "going",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.how_are_you_holding_up",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "how",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "are",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "holding",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "up",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.97,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.how_are_you_managing",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "how",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "are",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "managing",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.97,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.how_has_your_day_been",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "how",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "has",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "your",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "day",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "been",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.how_is_everything_going",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "how",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "is",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "everything",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "going",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.hows_everything_going",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "how's",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "everything",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "going",
                },
            },
            ["priority"] = 120,
        },
        {
            ["confidence"] = 0.97,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.you_doing_all_right",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "doing",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "all",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "right",
                },
            },
            ["priority"] = 120,
        },
    },
    ["responsePools"] = {
        {
            ["id"] = "semantic.accept",
            ["variants"] = {
                {
                    ["fallback"] = "Okay, I'll get started.",
                    ["id"] = "semantic.accept.dataset.pending_started",
                    ["priority"] = 1,
                    ["templateID"] = "semantic.accept.dataset.pending_started",
                    ["when"] = {
                        ["hasPendingRequest"] = true,
                    },
                },
                {
                    ["fallback"] = "All right. I can take care of that.",
                    ["id"] = "semantic.accept.dataset.pending_care",
                    ["priority"] = 1,
                    ["templateID"] = "semantic.accept.dataset.pending_care",
                    ["when"] = {
                        ["hasPendingRequest"] = true,
                    },
                },
            },
        },
        {
            ["id"] = "semantic.compliment",
            ["variants"] = {
                {
                    ["fallback"] = "That's kind of you. I appreciate it.",
                    ["id"] = "semantic.compliment.dataset.kind_of_you",
                    ["templateID"] = "semantic.compliment.dataset.kind_of_you",
                },
                {
                    ["fallback"] = "Aw, thank you. That means a lot.",
                    ["id"] = "semantic.compliment.dataset.means_a_lot",
                    ["templateID"] = "semantic.compliment.dataset.means_a_lot",
                },
            },
        },
        {
            ["id"] = "semantic.greeting",
            ["variants"] = {
                {
                    ["fallback"] = "Hey. How are you holding up?",
                    ["id"] = "semantic.greeting.dataset.holding_up",
                    ["templateID"] = "semantic.greeting.dataset.holding_up",
                },
                {
                    ["fallback"] = "Good to see you again.",
                    ["id"] = "semantic.greeting.dataset.good_to_see",
                    ["templateID"] = "semantic.greeting.dataset.good_to_see",
                },
                {
                    ["fallback"] = "Hey. How are things going?",
                    ["id"] = "semantic.greeting.dataset.how_things",
                    ["templateID"] = "semantic.greeting.dataset.how_things",
                },
            },
        },
        {
            ["id"] = "semantic.offer",
            ["variants"] = {
                {
                    ["fallback"] = "That would help a lot. Could I have some?",
                    ["id"] = "semantic.offer.dataset.hungry_share",
                    ["priority"] = 2,
                    ["templateID"] = "semantic.offer.dataset.hungry_share",
                    ["when"] = {
                        ["needType"] = "hunger",
                        ["needUrgency"] = {
                            "moderate",
                            "severe",
                            "emergency",
                            "critical",
                        },
                    },
                },
                {
                    ["fallback"] = "I'd appreciate a bite. Would you share?",
                    ["id"] = "semantic.offer.dataset.hungry_appreciate",
                    ["priority"] = 2,
                    ["templateID"] = "semantic.offer.dataset.hungry_appreciate",
                    ["when"] = {
                        ["needType"] = "hunger",
                        ["needUrgency"] = {
                            "moderate",
                            "severe",
                            "emergency",
                            "critical",
                        },
                    },
                },
            },
        },
        {
            ["id"] = "semantic.question.activity",
            ["variants"] = {
                {
                    ["fallback"] = "Just doing what I can to keep things moving.",
                    ["id"] = "semantic.question.activity.dataset.keep_moving",
                    ["templateID"] = "semantic.question.activity.dataset.keep_moving",
                },
                {
                    ["fallback"] = "A little bit of everything.",
                    ["id"] = "semantic.question.activity.dataset.bit_of_everything",
                    ["templateID"] = "semantic.question.activity.dataset.bit_of_everything",
                },
                {
                    ["fallback"] = "Just taking care of what needs doing.",
                    ["id"] = "semantic.question.activity.dataset.taking_care",
                    ["templateID"] = "semantic.question.activity.dataset.taking_care",
                },
            },
        },
        {
            ["id"] = "semantic.question.identity",
            ["variants"] = {
                {
                    ["fallback"] = "I keep my name to myself until I know someone better. What should I call you?",
                    ["id"] = "semantic.question.identity.dataset.stranger_alt_1",
                    ["templateID"] = "semantic.question.identity.stranger_alt_1",
                },
                {
                    ["fallback"] = "Let's get to know each other first. What do people call you?",
                    ["id"] = "semantic.question.identity.dataset.stranger_alt_2",
                    ["templateID"] = "semantic.question.identity.stranger_alt_2",
                },
                {
                    ["fallback"] = "I don't trust you enough to share my name. Who are you, really?",
                    ["id"] = "semantic.question.identity.dataset.wary_alt_1",
                    ["priority"] = 2,
                    ["templateID"] = "semantic.question.identity.wary_alt_1",
                    ["when"] = {
                        ["identityTrust"] = "untrustworthy",
                    },
                },
                {
                    ["fallback"] = "After that lie, I'm not telling you my name. Tell me the truth about yours.",
                    ["id"] = "semantic.question.identity.dataset.wary_alt_2",
                    ["priority"] = 2,
                    ["templateID"] = "semantic.question.identity.wary_alt_2",
                    ["when"] = {
                        ["identityTrust"] = "untrustworthy",
                    },
                },
            },
        },
        {
            ["id"] = "semantic.question.wellbeing",
            ["variants"] = {
                {
                    ["fallback"] = "I'm hanging in there. Thanks for asking.",
                    ["id"] = "semantic.question.wellbeing.dataset.hanging_in",
                    ["templateID"] = "semantic.question.wellbeing.dataset.hanging_in",
                },
                {
                    ["fallback"] = "Doing okay, all things considered.",
                    ["id"] = "semantic.question.wellbeing.dataset.all_things_considered",
                    ["templateID"] = "semantic.question.wellbeing.dataset.all_things_considered",
                },
                {
                    ["fallback"] = "I'm getting by, one day at a time. How about you?",
                    ["id"] = "semantic.question.wellbeing.dataset.getting_by",
                    ["templateID"] = "semantic.question.wellbeing.dataset.getting_by",
                },
                {
                    ["fallback"] = "I'm hungry, but I'll manage. If you have food to spare, I'd appreciate it.",
                    ["id"] = "semantic.question.wellbeing.dataset.hungry",
                    ["priority"] = 2,
                    ["templateID"] = "semantic.question.wellbeing.dataset.hungry",
                    ["when"] = {
                        ["needType"] = "hunger",
                        ["needUrgency"] = {
                            "moderate",
                            "severe",
                            "emergency",
                            "critical",
                        },
                    },
                },
                {
                    ["fallback"] = "I'm pretty thirsty. If you have water, could you spare some?",
                    ["id"] = "semantic.question.wellbeing.dataset.thirsty",
                    ["priority"] = 3,
                    ["templateID"] = "semantic.question.wellbeing.dataset.thirsty",
                    ["when"] = {
                        ["needType"] = "thirst",
                        ["needUrgency"] = {
                            "moderate",
                            "severe",
                            "emergency",
                            "critical",
                        },
                    },
                },
                {
                    ["fallback"] = "I'm tired, though I can manage for now.",
                    ["id"] = "semantic.question.wellbeing.dataset.tired",
                    ["priority"] = 2,
                    ["templateID"] = "semantic.question.wellbeing.dataset.tired",
                    ["when"] = {
                        ["needType"] = "fatigue",
                        ["needUrgency"] = {
                            "moderate",
                            "severe",
                            "emergency",
                            "critical",
                        },
                    },
                },
            },
        },
        {
            ["id"] = "semantic.refuse",
            ["variants"] = {
                {
                    ["fallback"] = "I can't take that on right now.",
                    ["id"] = "semantic.refuse.dataset.pending_unavailable",
                    ["priority"] = 1,
                    ["templateID"] = "semantic.refuse.dataset.pending_unavailable",
                    ["when"] = {
                        ["hasPendingRequest"] = true,
                    },
                },
                {
                    ["fallback"] = "Not this time. I have enough to manage.",
                    ["id"] = "semantic.refuse.dataset.pending_enough",
                    ["priority"] = 1,
                    ["templateID"] = "semantic.refuse.dataset.pending_enough",
                    ["when"] = {
                        ["hasPendingRequest"] = true,
                    },
                },
            },
        },
        {
            ["id"] = "semantic.thanks",
            ["variants"] = {
                {
                    ["fallback"] = "No problem at all.",
                    ["id"] = "semantic.thanks.dataset.no_problem",
                    ["templateID"] = "semantic.thanks.dataset.no_problem",
                },
                {
                    ["fallback"] = "Anytime.",
                    ["id"] = "semantic.thanks.dataset.anytime",
                    ["templateID"] = "semantic.thanks.dataset.anytime",
                },
                {
                    ["fallback"] = "Glad I could help.",
                    ["id"] = "semantic.thanks.dataset.glady",
                    ["templateID"] = "semantic.thanks.dataset.glady",
                },
            },
        },
    },
    ["source"] = {
        ["contentLicense"] = "Project Hoomans authored content",
        ["name"] = "Project Hoomans Common Interaction Seed",
        ["references"] = {
            {
                ["name"] = "DailyDialog",
                ["url"] = "https://aclanthology.org/I17-1099/",
                ["use"] = "Everyday dialogue-act coverage guidance; no corpus turns are copied.",
            },
            {
                ["name"] = "EmpatheticDialogues",
                ["url"] = "https://github.com/facebookresearch/EmpatheticDialogues",
                ["use"] = "Emotion-aware interaction coverage guidance; no corpus turns are copied.",
            },
        },
        ["version"] = "1",
    },
}
