-- Generated by tools/semantic_compiler/build.py; do not edit by hand.
-- Dialogue patterns shard 02; keep this file data-only.
return {
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.what_do_you_go_by",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "do",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "go",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "by",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.what_should_i_call_you",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "should",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "i",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "call",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.who_am_i_speaking_with",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "who",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "am",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "i",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "speaking",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "with",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.who_am_i_talking_to",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "who",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "am",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "i",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "talking",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "to",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.are_you_holding_up_okay",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "are",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "holding",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "up",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "okay",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.how_are_things_going",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "how",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "are",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "things",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "going",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.how_are_you_holding_up",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "how",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "are",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "holding",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "up",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.97,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.how_are_you_managing",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "how",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "are",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "managing",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.97,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.how_has_your_day_been",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "how",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "has",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "your",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "day",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "been",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.how_is_everything_going",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "how",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "is",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "everything",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "going",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.hows_everything_going",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "how's",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "everything",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "going",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.97,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "WELLBEING",
            },
            ["id"] = "pnc.dataset.question.wellbeing.you_doing_all_right",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "doing",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "all",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "right",
                },
            },
            ["priority"] = 120,
        },
}
