-- Generated by tools/semantic_compiler/build.py; do not edit by hand.
-- Dialogue patterns shard 01; keep this file data-only.
return {
    {
            ["confidence"] = 0.97,
            ["emit"] = {
                ["intent"] = "GREET",
                ["speechAct"] = "GREET",
            },
            ["id"] = "pnc.dataset.greeting.glad_to_see_you_again",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "glad",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "to",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "see",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "again",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "GREET",
                ["speechAct"] = "GREET",
            },
            ["id"] = "pnc.dataset.greeting.good_to_see_you_again",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "good",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "to",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "see",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "again",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "GREET",
                ["speechAct"] = "GREET",
            },
            ["id"] = "pnc.dataset.greeting.long_time_no_see",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "long",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "time",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "no",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "see",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "GREET",
                ["speechAct"] = "GREET",
            },
            ["id"] = "pnc.dataset.greeting.nice_to_see_you_again",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "nice",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "to",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "see",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "again",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.97,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "ACTIVITY",
            },
            ["id"] = "pnc.dataset.question.activity.what_are_you_focused_on",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "are",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "focused",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "on",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "ACTIVITY",
            },
            ["id"] = "pnc.dataset.question.activity.what_are_you_working_on",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "are",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "working",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "on",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "ACTIVITY",
            },
            ["id"] = "pnc.dataset.question.activity.what_have_you_been_doing_today",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "have",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "been",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "doing",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "today",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "ACTIVITY",
            },
            ["id"] = "pnc.dataset.question.activity.what_have_you_been_up_to_lately",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "have",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "been",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "up",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "to",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "lately",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.can_i_ask_your_name",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "can",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "i",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "ask",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "your",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "name",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.can_you_tell_me_your_name",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "can",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "tell",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "me",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "your",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "name",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.may_i_ask_your_name",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "may",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "i",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "ask",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "your",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "name",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.99,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.may_i_know_your_name",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "may",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "i",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "know",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "your",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "name",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.mind_telling_me_your_name",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "mind",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "telling",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "me",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "your",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "name",
                },
            },
            ["priority"] = 120,
        },
    {
            ["confidence"] = 0.98,
            ["emit"] = {
                ["intent"] = "QUESTION",
                ["speechAct"] = "QUESTION",
                ["subject"] = "IDENTITY",
            },
            ["id"] = "pnc.dataset.question.identity.what_do_people_call_you",
            ["match"] = {
                {
                    ["kind"] = "literal",
                    ["value"] = "what",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "do",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "people",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "call",
                },
                {
                    ["kind"] = "literal",
                    ["value"] = "you",
                },
            },
            ["priority"] = 120,
        },
}
