-- Generated by tools/semantic_compiler/build.py; do not edit by hand.
-- Selected lexical data is derived from Princeton WordNet.
-- WordNet source: https://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz
-- WordNet license: WordNet 3.0 license
-- Morphology: WordNet verb.exc plus allowlist-scoped regular forms, kept separate from action aliases.
-- SHA256 LICENSE: 7731175a77952e259390b496fab905e57118b8d19ad3a8383c67eee724ff443f
-- SHA256 data.verb: 7fff397e93b4fb152fdaee116747cf1c40d7badedccb4b63f5503e8e962d9102
-- SHA256 index.verb: c7c79b558d787f1e31c6f8b3eeadb8fcbb26a64545ecc1241e21d9b61f95ee8e
-- SHA256 verb.exc: dbbcf9a601b2d77e934e413b91d90e88ec7f933a8b77cfc00602a923b891b42c
-- Begin WordNet 3.0 license notice.
-- WordNet Release 3.0
--
-- This software and database is being provided to you, the LICENSEE, by  
-- Princeton University under the following license.  By obtaining, using  
-- and/or copying this software and database, you agree that you have  
-- read, understood, and will comply with these terms and conditions.:  
--   
-- Permission to use, copy, modify and distribute this software and  
-- database and its documentation for any purpose and without fee or  
-- royalty is hereby granted, provided that you agree to comply with  
-- the following copyright notice and statements, including the disclaimer,  
-- and that the same appear on ALL copies of the software, database and  
-- documentation, including modifications that you make for internal  
-- use or for distribution.  
--   
-- WordNet 3.0 Copyright 2006 by Princeton University.  All rights reserved.  
--   
-- THIS SOFTWARE AND DATABASE IS PROVIDED "AS IS" AND PRINCETON  
-- UNIVERSITY MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR  
-- IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, PRINCETON  
-- UNIVERSITY MAKES NO REPRESENTATIONS OR WARRANTIES OF MERCHANT-  
-- ABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE  
-- OF THE LICENSED SOFTWARE, DATABASE OR DOCUMENTATION WILL NOT  
-- INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS OR  
-- OTHER RIGHTS.  
--   
-- The name of Princeton University or Princeton may not be used in  
-- advertising or publicity pertaining to distribution of the software  
-- and/or database.  Title to copyright in this software, database and  
-- any associated documentation shall at all times remain with  
-- Princeton University and LICENSEE agrees to preserve same.
-- End WordNet 3.0 license notice.

return {
    source = {
        name = "Princeton WordNet",
        version = "3.0",
        license = "WordNet 3.0 license",
    },
    aliasesByConcept = {
        ["FETCH"] = {
            "bring",
            "fetch",
            "get",
            "grab",
            "pick up",
            "retrieve",
            "take hold of",
        },
        ["FOLLOW"] = {
            "follow",
        },
    },
    verbFormsBySurface = {
        ["bringing"] = {
            concept = "FETCH",
            lemma = "bring",
            form = "PROGRESSIVE",
        },
        ["brings"] = {
            concept = "FETCH",
            lemma = "bring",
            form = "THIRD_PERSON",
        },
        ["brought"] = {
            concept = "FETCH",
            lemma = "bring",
            form = "PAST",
        },
        ["fetched"] = {
            concept = "FETCH",
            lemma = "fetch",
            form = "PAST",
        },
        ["fetches"] = {
            concept = "FETCH",
            lemma = "fetch",
            form = "THIRD_PERSON",
        },
        ["fetching"] = {
            concept = "FETCH",
            lemma = "fetch",
            form = "PROGRESSIVE",
        },
        ["followed"] = {
            concept = "FOLLOW",
            lemma = "follow",
            form = "PAST",
        },
        ["following"] = {
            concept = "FOLLOW",
            lemma = "follow",
            form = "PROGRESSIVE",
        },
        ["follows"] = {
            concept = "FOLLOW",
            lemma = "follow",
            form = "THIRD_PERSON",
        },
        ["gets"] = {
            concept = "FETCH",
            lemma = "get",
            form = "THIRD_PERSON",
        },
        ["getting"] = {
            concept = "FETCH",
            lemma = "get",
            form = "PROGRESSIVE",
        },
        ["grabbed"] = {
            concept = "FETCH",
            lemma = "grab",
            form = "PAST",
        },
        ["grabbing"] = {
            concept = "FETCH",
            lemma = "grab",
            form = "PROGRESSIVE",
        },
        ["grabs"] = {
            concept = "FETCH",
            lemma = "grab",
            form = "THIRD_PERSON",
        },
        ["picked up"] = {
            concept = "FETCH",
            lemma = "pick up",
            form = "PAST",
        },
        ["picking up"] = {
            concept = "FETCH",
            lemma = "pick up",
            form = "PROGRESSIVE",
        },
        ["picks up"] = {
            concept = "FETCH",
            lemma = "pick up",
            form = "THIRD_PERSON",
        },
        ["retrieved"] = {
            concept = "FETCH",
            lemma = "retrieve",
            form = "PAST",
        },
        ["retrieves"] = {
            concept = "FETCH",
            lemma = "retrieve",
            form = "THIRD_PERSON",
        },
        ["retrieving"] = {
            concept = "FETCH",
            lemma = "retrieve",
            form = "PROGRESSIVE",
        },
        ["taken hold of"] = {
            concept = "FETCH",
            lemma = "take hold of",
            form = "PAST",
        },
        ["takes hold of"] = {
            concept = "FETCH",
            lemma = "take hold of",
            form = "THIRD_PERSON",
        },
        ["taking hold of"] = {
            concept = "FETCH",
            lemma = "take hold of",
            form = "PROGRESSIVE",
        },
        ["took hold of"] = {
            concept = "FETCH",
            lemma = "take hold of",
            form = "PAST",
        },
    },
}
