-- Each phrase has its own stable code and translation key.
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Positive/Praise/Helping/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Positive/Praise/Rescue/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Negative/Mockery/LostGear/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Negative/Mockery/Retreat/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Negative/Suspicion/ChangingStory/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Death/Report/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Death/Sacrifice/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Death/CorpseReaction/Relative/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Death/CorpseReaction/Friend/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Death/CorpseReaction/Comrade/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Death/CorpseReaction/Hostile/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Death/CorpseReaction/Neutral/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Neutral/Sighting/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Positive/Sympathy/Loss/01_PNC_GossipTemplate"
require "PNC/Conversation/Definitions/Memory/GossipTemplates/Negative/Warning/Danger/01_PNC_GossipTemplate"
return true
