PNC = PNC or {}
PNC.WorkDefinitions = PNC.WorkDefinitions or {}

local Definitions = PNC.WorkDefinitions

Definitions.STATIONS = {
    workshop = {
        id = "workshop",
        facilityId = "workshop",
        capability = "work.craft",
        role = "work.craft",
        legacyRoles = { "work.disassemble" },
        labelKey = "UI_PNC_Workshop_CraftingStation",
    },
    primitive_forge = {
        id = "primitive_forge", facilityId = "primitive_forge",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_PrimitiveForge",
        entityScript = "Base.Forge_Primitive_Forge",
        buildRecipeObjectInfoName = "Base.Forge_Primitive_Forge",
        requiredTechnology = nil,
        directWorkstation = true,
    },
    forge = {
        id = "forge", facilityId = "forge", capability = "work.craft",
        role = "work.craft", labelKey = "UI_PNC_Facility_Forge",
        entityScript = "Base.Forge",
        buildRecipeObjectInfoName = "Base.Forge",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    advanced_forge = {
        id = "advanced_forge", facilityId = "advanced_forge",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_AdvancedForge",
        entityScript = "Base.Advanced_Forge",
        buildRecipeObjectInfoName = "Base.Advanced_Forge",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    primitive_furnace = {
        id = "primitive_furnace", facilityId = "primitive_furnace",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_PrimitiveFurnace",
        entityScript = "Base.Primitive_Furnace",
        buildRecipeObjectInfoName = "Base.Primitive_Furnace",
        requiredTechnology = nil,
        directWorkstation = true,
    },
    furnace = {
        id = "furnace", facilityId = "furnace", capability = "work.craft",
        role = "work.craft", labelKey = "UI_PNC_Facility_Furnace",
        entityScript = "Base.Smelting_Furnace",
        buildRecipeObjectInfoName = "Base.Smelting_Furnace",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    advanced_furnace = {
        id = "advanced_furnace", facilityId = "advanced_furnace",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_AdvancedFurnace",
        entityScript = "Base.Blast_Furnace",
        buildRecipeObjectInfoName = "Base.Blast_Furnace",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    hand_press = {
        id = "hand_press", facilityId = "hand_press",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_HandPress",
        entityScript = "Base.Hand_Press",
        buildRecipeObjectInfoName = "Base.Hand_Press",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    pottery_bench = {
        id = "pottery_bench", facilityId = "pottery_bench",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_PotteryBench",
        entityScript = "Base.Pottery_Bench",
        buildRecipeObjectInfoName = "Base.Pottery_Bench",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    pottery_wheel = {
        id = "pottery_wheel", facilityId = "pottery_wheel",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_PotteryWheel",
        entityScript = "Base.Pottery_Wheel",
        buildRecipeObjectInfoName = "Base.Pottery_Wheel",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    kiln_small = {
        id = "kiln_small", facilityId = "kiln_small",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_KilnSmall",
        entityScript = "Base.Kiln_Small",
        buildRecipeObjectInfoName = "Base.Kiln_Small",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    kiln_large = {
        id = "kiln_large", facilityId = "kiln_large",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_KilnLarge",
        entityScript = "Base.Kiln_Large",
        buildRecipeObjectInfoName = "Base.Kiln_Large",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    dome_kiln = {
        id = "dome_kiln", facilityId = "dome_kiln",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_DomeKiln",
        entityScript = "Base.Dome_Kiln",
        buildRecipeObjectInfoName = "Base.Dome_Kiln",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    grindstone = {
        id = "grindstone", facilityId = "grindstone",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_Grindstone",
        entityScript = "Base.Grindstone",
        buildRecipeObjectInfoName = "Base.Grindstone",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    metal_bandsaw = {
        id = "metal_bandsaw", facilityId = "metal_bandsaw",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_MetalBandsaw",
        entityScript = "Base.MetalBandsaw",
        buildRecipeObjectInfoName = "Base.MetalBandsaw",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    spinning_wheel = {
        id = "spinning_wheel", facilityId = "spinning_wheel",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_SpinningWheel",
        entityScript = "Base.Spinning_Wheel",
        buildRecipeObjectInfoName = "Base.Spinning_Wheel",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    loom = {
        id = "loom", facilityId = "loom", capability = "work.craft",
        role = "work.craft", labelKey = "UI_PNC_Facility_Loom",
        entityScript = "Base.Loom",
        buildRecipeObjectInfoName = "Base.Loom",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    simple_loom = {
        id = "simple_loom", facilityId = "simple_loom",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_SimpleLoom",
        entityScript = "Base.SimpleLoom",
        buildRecipeObjectInfoName = "Base.SimpleLoom",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    stone_mill = {
        id = "stone_mill", facilityId = "stone_mill",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_StoneMill",
        entityScript = "Base.Stone_Mill",
        buildRecipeObjectInfoName = "Base.Stone_Mill",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    stone_quern = {
        id = "stone_quern", facilityId = "stone_quern",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_StoneQuern",
        entityScript = "Base.Stone_Quern",
        buildRecipeObjectInfoName = "Base.Stone_Quern",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    churn_bucket = {
        id = "churn_bucket", facilityId = "churn_bucket",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_ChurnBucket",
        entityScript = "Base.ChurnBucket",
        buildRecipeObjectInfoName = "Base.ChurnBucket",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    drying_rack = {
        id = "drying_rack", facilityId = "drying_rack",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_DryingRack",
        entityScript = "Base.Drying_Rack",
        buildRecipeObjectInfoName = "Base.Drying_Rack",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    simple_drying_rack = {
        id = "simple_drying_rack", facilityId = "simple_drying_rack",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_SimpleDryingRack",
        entityScript = "Base.Simple_Drying_Rack",
        buildRecipeObjectInfoName = "Base.Simple_Drying_Rack",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
    herb_drying_rack = {
        id = "herb_drying_rack", facilityId = "herb_drying_rack",
        capability = "work.craft", role = "work.craft",
        labelKey = "UI_PNC_Facility_HerbDryingRack",
        entityScript = "Base.Herb_Drying_Rack",
        buildRecipeObjectInfoName = "Base.Herb_Drying_Rack",
        requiredTechnology = "facility:workshop",
        directWorkstation = true,
    },
}

Definitions.CRAFTING_SKILL_ORDER = {
    "Blacksmithing", "Carpentry", "Carving", "Cooking", "Electrical",
    "Glassmaking", "Knapping", "Masonry", "Mechanics", "Pottery",
    "Tailoring", "Welding",
}

Definitions.STATION_SKILL_FALLBACKS = {
    primitive_forge = { "Blacksmithing", "Welding" },
    forge = { "Blacksmithing", "Welding" },
    advanced_forge = { "Blacksmithing", "Welding" },
    primitive_furnace = { "Blacksmithing", "Glassmaking" },
    furnace = { "Blacksmithing", "Glassmaking" },
    advanced_furnace = { "Blacksmithing", "Glassmaking" },
    hand_press = { "Carpentry", "Blacksmithing" },
    pottery_bench = { "Pottery" },
    pottery_wheel = { "Pottery" },
    kiln_small = { "Pottery", "Glassmaking" },
    kiln_large = { "Pottery", "Glassmaking" },
    dome_kiln = { "Pottery", "Glassmaking" },
    grindstone = { "Blacksmithing", "Welding" },
    metal_bandsaw = { "Welding", "Mechanics" },
    spinning_wheel = { "Tailoring" },
    loom = { "Tailoring" },
    simple_loom = { "Tailoring" },
    stone_mill = { "Cooking" },
    stone_quern = { "Cooking", "Masonry" },
    churn_bucket = { "Cooking" },
    drying_rack = { "Tailoring", "Cooking" },
    simple_drying_rack = { "Tailoring", "Cooking" },
    herb_drying_rack = { "Cooking", "Tailoring" },
}

for stationId, skills in pairs(Definitions.STATION_SKILL_FALLBACKS) do
    local station = Definitions.STATIONS[stationId]
    if station then
        station.specializationSkills = skills
        station.productionSkillId = skills[1]
    end
end

return Definitions
