-- Stable construction queueing entry point.
if PsychopatzCore and PsychopatzCore.RuntimeRole
    and not PsychopatzCore.RuntimeRole.AllowsServerCode() then return end
require "PNC/Production/ConstructionService/ConstructionService_Queueing/PNC_ConstructionService_Queueing_Build"
require "PNC/Production/ConstructionService/ConstructionService_Queueing/PNC_ConstructionService_Queueing_Deconstruct"
require "PNC/Production/ConstructionService/ConstructionService_Queueing/PNC_ConstructionService_Queueing_Reconstruct"
return PNC.ConstructionService
