PNC = PNC or {}
PNC.Const = PNC.Const or {}

local Const = PNC.Const

Const.MELEE_RANGE = 1.3
Const.MELEE_HIT_TOLERANCE = 0.12
Const.MELEE_APPROACH_STOP_DISTANCE = 0.92
-- Formation slots sit about 1.05 tiles from a target. Keep the commit window
-- outside that ring while retaining margin inside the authoritative hit reach.
Const.MELEE_COMMIT_RANGE = 1.15
Const.RANGED_RANGE = 8.5
Const.RANGED_MIN_STANDOFF = 2.2
Const.RANGED_PREFERRED_MIN_DISTANCE = 5.0
Const.RANGED_RETREAT_STEP = 3.2
Const.RANGED_PRESSURE_COUNT = 2
Const.RANGED_AIM_BASE_MS = 460
Const.RANGED_AIM_MIN_MS = 140
Const.RANGED_AIM_SKILL_REDUCTION_MS = 32
Const.RANGED_AIM_DISTANCE_PENALTY_MS = 22
Const.RANGED_AIM_PRESSURE_PENALTY_MS = 65
Const.RANGED_AIM_MOVE_TOLERANCE = 0.35
Const.RANGED_FRIENDLY_FIRE_CORRIDOR = 0.62
Const.RANGED_FIRE_LANE_CACHE_MS = 120
Const.RANGED_FIRE_LANE_STRAFE_DISTANCE = 1.6
Const.RANGED_FIRE_LANE_LOCK_MS = 500
Const.RANGED_RELOAD_BREAK_DISTANCE = 2.35
Const.RANGED_RELOAD_BREAK_PRESSURE_COUNT = 2
Const.COMBAT_BLOCK_LOG_REPEAT_MS = 5000
Const.GUARD_RADIUS = 3.0
Const.GUARD_STOP_DISTANCE = 0.45
Const.GUARD_ENGAGE_RADIUS = 3.0
Const.CAMP_RADIUS = 3.0
Const.CAMP_STOP_DISTANCE = 0.45
Const.CAMP_ENGAGE_RADIUS = 3.0
Const.FOLLOW_DISTANCE = 1.8
Const.FOLLOW_WALK_DISTANCE = 4.0
-- Followers walk with the group and reserve running for a genuine separation.
-- The wider exit band prevents walk/run oscillation around one threshold.
Const.FOLLOW_RUN_DISTANCE = 10.0
Const.FOLLOW_CATCHUP_EXIT_DISTANCE = 6.0
Const.FOLLOW_OWNER_COMBAT_MEMORY_MS = 1400
Const.FOLLOW_PATH_BLOCKED_COOLDOWN_MS = 1200
Const.NPC_GROUNDED_RECOVERY_MS = 1400
Const.NPC_GROUNDED_COUNTER_STAGGER_CHANCE = 0.40
Const.NPC_GROUNDED_COUNTER_STAGGER_RANGE = 2.25
Const.NPC_GROUNDED_COUNTER_STAGGER_DURATION_MS = 650
Const.NPC_GROUNDED_COUNTER_STAGGER_TIMEOUT_MS = 1400
-- Follow movement remains responsive at 5 decisions per second while leaving
-- enough room for the native route and server scheduler to advance between
-- behavior passes. Threats still use their own urgent signal gates.
Const.FOLLOW_DECISION_INTERVAL_MS = 200
Const.FOLLOW_TICK_INTERVAL_MS = 100
Const.FOLLOW_IDLE_TICK_INTERVAL_MS = 350
Const.FOLLOW_THREAT_ACTIVE_SCAN_MS = 150
Const.FOLLOW_THREAT_IDLE_SCAN_MS = 350
-- Seated NPCs only need a lightweight local safety check. Keep acquisition
-- slower than combat while validating an active threat often enough to stop
-- promptly when it is no longer hostile.
Const.SEATED_THREAT_SCAN_MS = 750
Const.SEATED_THREAT_VALIDATE_MS = 250
Const.FOLLOW_COMBAT_LEASH_DISTANCE = 5.5
Const.FOLLOW_OWNER_MOVE_EPSILON = 0.08
Const.FOLLOW_HORDE_AVOID_RADIUS = 6.5
Const.FOLLOW_HORDE_AVOID_COUNT = 3
Const.FOLLOW_HORDE_NEAR_DISTANCE = 2.4
Const.FOLLOW_HORDE_STEER_DISTANCE = 1.8
Const.FOLLOW_HORDE_SCAN_MS = 150
Const.FOLLOW_COMBAT_HORDE_CACHE_MS = 350
Const.FOLLOW_HORDE_STEER_MS = 700
-- Combat retreats for followers may create space, but must remain inside the
-- same owner leash used by follow combat arbitration.
Const.FOLLOW_RETREAT_MAX_DISTANCE = Const.FOLLOW_COMBAT_LEASH_DISTANCE
Const.FOLLOW_SLOT_DISTANCE = 2.25
Const.FOLLOW_SLOT_LATERAL = 1.15
Const.FOLLOW_SLOT_ROW_DISTANCE = 0.85
Const.FOLLOW_SLOT_ROW_LATERAL = 0.25
Const.FOLLOW_SLOT_STOP_DISTANCE = 0.35
Const.FOLLOW_INDOOR_APPROACH_DISTANCE = 1.6
Const.FOLLOW_PERSONAL_SPACE_MIN = 1.25
Const.FOLLOW_FORMATION_CACHE_MS = 250
Const.FOLLOW_FORMATION_MOVING_CACHE_MS = 300
Const.FOLLOW_FORMATION_IDLE_CACHE_MS = 1000
Const.FOLLOW_RETARGET_OWNER_DISTANCE = 0.75
Const.FOLLOW_RETARGET_MAX_MS = 800
Const.FOLLOW_MOVE_INTENT_EPSILON = 0.35
Const.FOLLOW_MOVE_INTENT_REFRESH_MS = 2000
Const.ANIMATION_IDLE_SCENE_MIN_MS = 8000
Const.ANIMATION_IDLE_SCENE_JITTER_MS = 12000
Const.FOLLOW_IDLE_ENTER_DISTANCE = 2.4
Const.FOLLOW_IDLE_EXIT_DISTANCE = 3.2
Const.FOLLOW_VEHICLE_BOARD_DISTANCE = 3.2
Const.FOLLOW_VEHICLE_TICK_MS = 100
Const.VEHICLE_RESERVATION_AUDIT_MS = 10000
Const.VEHICLE_RESERVATION_ITEM_TYPE = "PNC.VehicleSeatReservation"
Const.PATROL_REACHED_DISTANCE = 0.8
Const.ROAM_DEFAULT_RADIUS = 6.0
Const.ROAM_REACHED_DISTANCE = 1.0
Const.ROAM_TARGET_RADIUS = 12.0
Const.ROAM_PAUSE_MIN_MS = 5000
Const.ROAM_PAUSE_MAX_MS = 12000
Const.ROAM_THREAT_MOVING_SCAN_MS = 250
Const.ROAM_THREAT_IDLE_SCAN_MS = 500
Const.ROAM_IDLE_TICK_INTERVAL_MS = 500
Const.COMPANION_COMMAND_RADIUS = 20
Const.INVENTORY_INTERACTION_RADIUS = 3.0
Const.INVENTORY_TRANSFER_MAX_ITEMS = 256
Const.INVENTORY_TRANSFER_MAX_QUANTITY = 1024
Const.INVENTORY_HARD_CAPACITY_MULTIPLIER = 3.0
Const.INVENTORY_HARD_CAPACITY = 50
Const.INVENTORY_ITEM_STATE_MAX_MODDATA_KEYS = 64
Const.INVENTORY_ITEM_STATE_MAX_STRING_LENGTH = 1024
Const.COMPANION_COMMAND_FEEDBACK_MS = 5000
Const.COMPANION_AVOID_THREAT_RADIUS = 10
Const.COMPANION_AVOID_THREAT_DISTANCE = 5
Const.COMPANION_AVOID_THREAT_LOCK_MS = 750
PNC = PNC or {}
PNC.Const = PNC.Const or {}

local Const = PNC.Const
