PNC = PNC or {}
PNC.Const = PNC.Const or {}

local Const = PNC.Const

-- Recovery retreat is an absolute reserve rule. NPC maximum stamina scales
-- with skills, so a ratio made trained NPCs flee while they still had plenty
-- of usable stamina.
Const.COMBAT_RETREAT_STAMINA_CURRENT = 20
Const.COMBAT_RETREAT_STAMINA_RATIO = 0.10
Const.COMBAT_REENGAGE_STAMINA_RATIO = 0.28
-- Low-stamina melee uses a short counter window, then creates only enough
-- space to clear the red defense circle and recovers before re-engaging.
Const.COMBAT_EXHAUSTED_COUNTER_MS = 1800
Const.COMBAT_EXHAUSTED_REENGAGE_CURRENT = 35
Const.COMBAT_RETREAT_SAFETY_BUFFER = 0.25
Const.COMBAT_SURROUND_RADIUS = 1.8
Const.COMBAT_SURROUND_COUNT = 3
Const.COMBAT_PRESSURE_RADIUS = 3.0
Const.COMBAT_PRESSURE_COUNT = 4
Const.COMBAT_HORDE_RADIUS = 5.5
-- A reactive retreat needs a real horde, not merely a crowded melee bubble.
Const.COMBAT_HORDE_COUNT = 4
Const.COMBAT_TARGET_CROWD_RADIUS = 2.2
Const.COMBAT_TARGET_CROWD_COUNT = 3
Const.COMBAT_KITE_MELEE_ENTER_BUFFER = 0.25
Const.COMBAT_KITE_MELEE_HOLD_BUFFER = 0.45
Const.COMBAT_KITE_MELEE_STOP_BUFFER = 0.16
Const.COMBAT_KITE_RETREAT_LOCK_MS = 1100
Const.COMBAT_RETREAT_STALL_MS = 900
Const.COMBAT_RETREAT_RETRY_MS = 800
Const.COMBAT_RETREAT_PROGRESS_DISTANCE = 0.18
Const.MIXED_MELEE_SWITCH_RANGE = 2.4
Const.MIXED_MELEE_FALLBACK_RANGE = 4.0
Const.COMBAT_KITE_DAMAGE_PRESSURE_MS = 2500
Const.COMBAT_KITE_DAMAGE_LOCK_MS = 900
Const.COMBAT_KITE_DAMAGE_DISTANCE = 2.2
Const.COMBAT_KITE_NEAR_MISS_WINDOW_MS = 1400
Const.COMBAT_SHOVE_RANGE = 1.35
Const.COMBAT_SHOVE_PRESSURE_COUNT = 2
Const.COMBAT_TACTICAL_RETREAT_MIN_PRESSURE = 2
Const.COMBAT_GROUND_FINISHER_MAX_PRESSURE = 1
Const.COMBAT_FORMATION_QUERY_RADIUS = 2.4
Const.COMBAT_FORMATION_SLOT_RADIUS = 1.05
Const.COMBAT_TACTICAL_DIAGNOSTIC_MS = 200
Const.COMBAT_DEBUG_CONE_RADIUS = 8.5
Const.COMBAT_DEBUG_CONE_HALF_ANGLE_DEGREES = 55
Const.COMBAT_DEBUG_VISIBLE_ZOMBIE_LIMIT = 6