PNC = PNC or {}
PNC.Const = PNC.Const or {}

local Const = PNC.Const

Const.LIVE_WALK_STEP = 0.09
Const.LIVE_RUN_STEP = 0.14
Const.ABSTRACT_TRAVEL_STEP = 5.0
Const.UNARMED_DAMAGE = 3
Const.UNARMED_GROUND_DAMAGE = 5
Const.UNARMED_COOLDOWN_MS = 1400
Const.REVIVE_HP = 10
Const.REVIVE_PROTECTION_MS = 3000
Const.REVIVE_BANDAGE_TYPE = "Base.Bandage"
Const.REVIVE_BANDAGE_COUNT = 5
Const.REVIVE_RANGE = 3.0
Const.BANDAGE_TYPE = "Base.Bandage"
Const.BANDAGE_TYPES = {
    "Base.AlcoholBandage", "Base.Bandage", "Base.Bandaid",
    "Base.AlcoholRippedSheets", "Base.RippedSheets",
}
Const.BANDAGE_RANGE = 3.0
Const.BANDAGE_COMPLETION_SOUND = "PNC_BandageComplete"
Const.BANDAGE_COMPLETION_FEEDBACK_MS = 5000
Const.INCAPACITATED_RECOVERY_HP = 5
Const.BANDAGE_HEAL_PER_WORLD_HOUR = 1.5
Const.BANDAGE_FIRST_AID_HEAL_BONUS = 0.25
Const.BANDAGE_DIRTY_AFTER_WORLD_HOURS = 8
Const.DEBUG_BANDAGE_ALMOST_DIRTY_WORLD_HOURS = 0.02
Const.SELF_BANDAGE_BASE_DURATION_MS = 6500
Const.SELF_BANDAGE_FIRST_AID_REDUCTION_MS = 350
Const.SELF_BANDAGE_MIN_DURATION_MS = 3000
Const.SELF_BANDAGE_RETRY_MS = 5000
Const.SELF_BANDAGE_THREAT_RADIUS = 10
-- Must match the red combat-defense circle. Treatment is safe only while no
-- hostile occupies this personal-space radius.
Const.SELF_BANDAGE_INTERRUPT_RADIUS = 2.2
Const.SELF_BANDAGE_RETREAT_DISTANCE = 5
Const.SELF_BANDAGE_RETREAT_STOP_DISTANCE = 1
Const.ABSTRACT_SELF_BANDAGE_INTERVAL_MS = 30000
Const.WOUND_BLEED_UPDATE_MS = 1000
Const.WOUND_DIRTY_FLUSH_MS = 5000
Const.DEATH_MARKER_MISSING_GRACE_MS = 5000
Const.INCAP_SHOVE_RANGE = 1.15
Const.INCAP_SHOVE_COOLDOWN_MS = 1200

Const.DOWNED_TIMEOUT_MS = 30000
Const.INCAPACITATED_TIMEOUT_MS = 30000
Const.INCAPACITATED_GRACE_MS = 1500
Const.INCAPACITATED_HP = 1
Const.INCAPACITATED_ENGINE_BUFFER = 1000
Const.DEBUG_COMBAT_HOLD_MS = 2500
Const.DEFAULT_HP_MAX = 100
Const.DEFAULT_ENGINE_BUFFER = 1000
Const.RECENT_DAMAGE_SHOW_MS = 4000
Const.PLAYER_HIT_DAMAGE_SCALE = 10
Const.PLAYER_HIT_DAMAGE_MAX = 50
Const.PLAYER_HIT_MELEE_RANGE = 3.0
Const.PLAYER_HIT_RANGED_RANGE = 20.0
Const.PLAYER_HIT_REPORT_COOLDOWN_MS = 80
Const.ZOMBIE_TARGET_RADIUS = 12
Const.TARGET_VISUAL_MEMORY_MS = 2200
Const.TARGET_REASSESS_MS = 350
Const.TARGET_IMMEDIATE_THREAT_RADIUS = 6.0
-- Server zombie aggro records are refreshed continuously while a zombie owns
-- an NPC pursuit lease. Perception uses this short window in multiplayer,
-- where the zombie's unsupported IsoZombie-shaped engine target stays unset.
Const.ZOMBIE_ATTACKER_OBSERVATION_MS = 1500
Const.TARGET_SWITCH_DISTANCE_RATIO = 0.72
Const.TARGET_RECENT_ATTACKER_MS = 5000
Const.ZOMBIE_AGGRO_RADIUS = 14
Const.ZOMBIE_AGGRO_KEEP_RADIUS = 2.4
Const.ZOMBIE_TARGET_PLAYER_KEEP_RADIUS = 2.0
Const.ZOMBIE_NPC_AGGRO_LEASE_MS = 8000
Const.ZOMBIE_NPC_PATH_REFRESH_MS = 350
Const.ZOMBIE_NPC_PATH_REFRESH_DISTANCE = 0.6
Const.ZOMBIE_ATTACK_RANGE = 0.95
Const.ZOMBIE_ATTACK_COOLDOWN_MS = 1500
Const.ZOMBIE_ATTACK_DAMAGE = 12
Const.ZOMBIE_BITE_APPLY_DELAY_MS = 450
Const.ZOMBIE_BITE_CLEAR_DELAY_MS = 700
Const.ZOMBIE_BITE_APPLY_TICK = 14
Const.ZOMBIE_BITE_CLEAR_TICK = 16
Const.ZOMBIE_BITE_DISTANCE = 0.8
-- NPC combat defense is evaluated against zombies inside this body-centered
-- radius.  The same value is sent to the combat overlay so the calculation is
-- visible rather than being an invisible balance rule.
Const.NPC_ZOMBIE_DEFENSE_RADIUS = 2.2
Const.NPC_ZOMBIE_DEFENSE_FITNESS_BASE = 0.90
Const.NPC_ZOMBIE_DEFENSE_FITNESS_STEP = 0.04
Const.NPC_ZOMBIE_DEFENSE_FITNESS_TWO_CHANCE = 0.98
Const.NPC_ZOMBIE_DEFENSE_HIGH_FITNESS_STEP = 0.0015
Const.NPC_ZOMBIE_DEFENSE_CROWD_PENALTY = 0.14
Const.NPC_ZOMBIE_DEFENSE_MIN_CROWD_PENALTY = 0.075
Const.NPC_ZOMBIE_DEFENSE_PUSH_CHANCE = 0.50
Const.NPC_ZOMBIE_DEFENSE_MIN_CHANCE = 0.05
Const.NPC_ZOMBIE_DEFENSE_MAX_CHANCE = 0.995
Const.NPC_ZOMBIE_DEFENSE_REFRESH_MS = 200
Const.STEALTH_DISCOVERY_RADIUS = 10
Const.STEALTH_BREAK_CONTACT_DISTANCE = 1.2
Const.STAMINA_MELEE_COST = 20
Const.STAMINA_RANGED_COST = 10
Const.STAMINA_DOWNED_SHOVE_COST = 8
Const.STAMINA_ATTACK_MIN_RESERVE = 10
Const.STAMINA_RECOVERY_IDLE = 7.0
Const.STAMINA_RECOVERY_MOVING = 4.5
Const.STAMINA_RECOVERY_COMBAT = 3.0
Const.STAMINA_RECOVERY_DOWNED = 2.5
Const.STAMINA_VISIBLE_MS = 4000
Const.STAMINA_MOVE_DRAIN_WALK = 3.0
Const.STAMINA_MOVE_DRAIN_RUN = 10.0
Const.STAMINA_MOVE_DRAIN_SNEAK = 4.0
Const.STAMINA_MOVE_DRAIN_CRAWL = 2.2
Const.STAMINA_MOVE_DRAIN_RECOVERY_WALK = 1.4
Const.STAMINA_MOVE_DRAIN_RECOVERY_SNEAK = 1.8
Const.STAMINA_MOVE_PROGRESS_LEASE_MS = 750
Const.STAMINA_MOVE_EXHAUST_PAUSE = 0.25
Const.STAMINA_MOVE_EXHAUST_RESUME = 0.40
Const.STAMINA_MOVE_RECOVERY_PAUSE = 0.35
Const.STAMINA_MOVE_RECOVERY_RESUME = 0.50
Const.STAMINA_MOVE_CRAWL_PAUSE = 0.60
Const.STAMINA_MOVE_CRAWL_RESUME = 0.75
Const.STAMINA_SPRINT_BREATHER_MS = 900
Const.ENCUMBRANCE_SEVERE_RATIO = 1.75
Const.ENCUMBRANCE_DAMAGE_INTERVAL_MS = 5000
Const.ENCUMBRANCE_DAMAGE_AMOUNT = 1.0
Const.ENCUMBRANCE_DAMAGE_FLOOR_RATIO = 0.75