PNC = PNC or {}
PNC.Const = PNC.Const or {}

local Const = PNC.Const

Const.PRESENCE_LIVE = "live"
Const.PRESENCE_ABSTRACT = "abstract"
Const.PRESENCE_CORPSE = "corpse"

Const.TACTICAL_CLASS_COLONIST = "colonist"
Const.TACTICAL_CLASS_NEUTRAL = "neutral"
Const.TACTICAL_CLASS_HOSTILE = "hostile"

Const.ORDER_FOLLOW = "follow"
Const.ORDER_CAMP = "camp"
Const.ORDER_GUARD = "guard"
Const.ORDER_PATROL = "patrol"
Const.ORDER_ROAM = "roam"
Const.ORDER_HOSTILE_ROAM = "hostile_roam"
Const.ORDER_HOSTILE_HUNT = "hostile_hunt"
Const.ORDER_TRAVEL = "travel"
Const.ORDER_SCAVENGE = "scavenge"
Const.ORDER_LUMBER = "lumber"
Const.ORDER_FISHING = "fishing"

Const.FISHING_DEFAULT_RADIUS = 16
Const.FISHING_ZONE_RADIUS = 12
Const.FISHING_MAX_ZONE_TILES = 10000
Const.FISHING_MAX_WORKERS = 16
Const.FISHING_WORK_POINTS_PER_SECOND = 5
Const.FISHING_REQUIRED_WORK_POINTS = 100
Const.FISHING_BASE_CATCH_CHANCE = 0.25
Const.FISHING_SKILL_CATCH_BONUS = 0.05
Const.FISHING_FATIGUE_STOP = 0.70

Const.SCAVENGE_DEFAULT_RADIUS = 12
Const.SCAVENGE_MAX_RADIUS = 24
Const.SCAVENGE_MAX_CANDIDATES = 256
Const.SCAVENGE_MAX_MANIFEST_ENTRIES = 512
Const.SCAVENGE_CAPACITY_STOP_RATIO = 1.25

Const.LUMBER_DEFAULT_RADIUS = 12
Const.LUMBER_MAX_RADIUS = 32
Const.LUMBER_MAX_ZONE_TILES = 10000

Const.ATTACK_TYPE_AUTO = "auto"
Const.ATTACK_TYPE_MELEE = "melee"
Const.ATTACK_TYPE_RANGED = "ranged"
Const.ATTACK_TYPE_NONE = "none"

Const.JOB_ROAM = "RoamArea"
Const.JOB_AT_CAMP = "AtCamp"
Const.ROAM_MODE_AREA = "area"
Const.ROAM_MODE_PLAYER = "player"
Const.ROAM_MODE_ROAD = "road"
Const.ROAM_MODE_SHELTER = "shelter"
PNC = PNC or {}
PNC.Const = PNC.Const or {}

local Const = PNC.Const
