PNC = PNC or {}
PNC.Const = PNC.Const or {}

local Const = PNC.Const

Const.CLIENT_INTERP_BASE_MS = 150
Const.CLIENT_INTERP_MOVE_MIN_MS = 200
Const.CLIENT_INTERP_STALE_MS = 2200
Const.CLIENT_INTERP_SNAP_DISTANCE = 5.0
Const.CLIENT_FACING_REASSERT_MS = 220
Const.CLIENT_LOCOMOTION_FACING_MS = 40
Const.CLIENT_BODY_SCAN_MS = 750
Const.CLIENT_BODY_SCAN_UNRESOLVED_MS = 200
Const.CLIENT_LOCAL_SNAPSHOT_SCAN_MS = 50
Const.CLIENT_LOCAL_SNAPSHOT_ATTACK_MS = 50
Const.CLIENT_LOCAL_SNAPSHOT_MOVE_MS = 150
Const.CLIENT_LOCAL_SNAPSHOT_IDLE_MS = 500
Const.CLIENT_LOCAL_SNAPSHOT_ABSTRACT_MS = 2000
Const.CLIENT_LOCAL_VISUAL_MAINTAIN_MS = 250
-- Remote clients receive engine-owned IsoZombie movement separately from
-- these roster snapshots. Keep presentation responsive without replaying
-- the full visual reconciliation on every render tick.
Const.CLIENT_REMOTE_SNAPSHOT_ACTIVE_MS = 100
Const.CLIENT_REMOTE_SNAPSHOT_MOVE_MS = 150
Const.CLIENT_REMOTE_SNAPSHOT_IDLE_MS = 500
Const.CLIENT_REMOTE_FACING_MOVE_MS = 100
Const.CLIENT_REMOTE_FACING_IDLE_MS = 220
Const.CLIENT_REMOTE_NATIVE_BIND_MS = 250
Const.CLIENT_REMOTE_STATE_PRUNE_MS = 5000
Const.BODY_AUDIT_INTERVAL_MS = 250
Const.CORPSE_AUDIT_INTERVAL_MS = 1000
Const.CORPSE_AUDIT_BATCH_SIZE = 12
Const.CORPSE_REANIMATE_RETRY_MAX = 3
Const.CORPSE_REANIMATE_RETRY_MS = 2000
Const.BODY_TAG_VERSION = 1
Const.BODY_SHELL_VERSION = 1
Const.BODY_SHELL_RESPAWN_DELAY_MS = 50
Const.BODY_SHELL_MAINTENANCE_MS = 1000
Const.BODY_SHELL_STARTUP_PASSES = 3
Const.BITE_RELEASE_TIMEOUT_MS = 650
Const.INVENTORY_OPLOG_MAX = 32
Const.ROSTER_CHUNK_SIZE = 50
Const.ROSTER_DELTA_INTERVAL_MS = 10000
Const.INTEREST_REFRESH_MS = 1000
Const.INTEREST_ENTER_DISTANCE = 48
Const.INTEREST_LEAVE_DISTANCE = 56
Const.CHARACTER_DETAIL_DISTANCE = 5
