PNC = PNC or {}
PNC.Const = PNC.Const or {}

local Const = PNC.Const


Const.ABSTRACT_TRAVEL_SPEED = 1.6666667
Const.TRAVEL_SCHEMA_VERSION = 2
Const.TRAVEL_API_VERSION = 2
Const.TRAVEL_DEFAULT_ARRIVAL_ACTION = "roam"
Const.TRAVEL_ROUTE_MAX_POINTS = 128
Const.TRAVEL_METADATA_MAX_DEPTH = 3
Const.TRAVEL_METADATA_MAX_ENTRIES = 64
Const.TRAVEL_SPEED_WALK_TILES_PER_HOUR = 300
Const.TRAVEL_SPEED_RUN_TILES_PER_HOUR = 480
Const.TRAVEL_SPEED_VEHICLE_TILES_PER_HOUR = 1500
Const.TRAVEL_ARRIVAL_RADIUS = 1.0
Const.TRAVEL_POSITION_REFRESH_MS = 250
Const.TRAVEL_MAP_LABEL_MIN_ZOOM = 10
Const.LIVE_TRAVEL_STEALTH_NEAR_RADIUS = 7
Const.LIVE_TRAVEL_STEALTH_HORDE_RADIUS = 12
Const.LIVE_TRAVEL_STEALTH_HORDE_COUNT = 3
Const.LIVE_TRAVEL_STEALTH_SCAN_MS = 350
Const.LIVE_TRAVEL_STEALTH_CLEAR_DELAY_MS = 2500
Const.MAP_COMMAND_MAX_SELECTION = 32
Const.MAP_COMMAND_COORDINATE_LIMIT = 1000000
Const.MAP_PRESENTATION_MAX_KNOWN_PLAYERS = 64
Const.MAP_PRESENTATION_ROLE_MAX_LENGTH = 32
Const.MAP_PRESENTATION_ICON_MAX_LENGTH = 64
Const.ENGINE_PATH_REQUEST_BUDGET_WINDOW_MS = 100
Const.ENGINE_PATH_REQUEST_BUDGET_PER_WINDOW = 1
Const.ENGINE_PATH_REQUEST_TIMEOUT_MS = 2500
Const.ENGINE_PATH_ROUTE_TIMEOUT_MS = 15000
Const.ENGINE_PATH_TRAVERSAL_TIMEOUT_MS = 3000
Const.ENGINE_PATH_REPLAN_MS = 1000
Const.ENGINE_PATH_TARGET_REPLAN_DISTANCE = 1.5
-- Bandits completes a Move task as soon as Behavior2 reports Failed. Allow
-- one retry for a door/window world-state change, then stop the identical
-- destination from generating path requests every few seconds.
Const.ENGINE_PATH_FAILURE_LIMIT = 2
Const.ENGINE_PATH_BLOCKED_GOAL_COOLDOWN_MS = 10000
Const.ENGINE_PATH_BLOCKED_GOAL_CHANGE_DISTANCE = 1.5
Const.ENGINE_PATH_MIN_ROUTE_DISTANCE = 1.0
Const.CLIENT_NATIVE_PATH_STALL_MS = 3000
Const.CLIENT_NATIVE_PATH_RETRY_BASE_MS = 350
Const.CLIENT_NATIVE_PATH_RETRY_MAX_MS = 4000
Const.CLIENT_NATIVE_PATH_REQUEST_GRACE_MS = 900
Const.CLIENT_NATIVE_MOVEMENT_LEASE_MS = 750
Const.BUMP_RELEASE_HARD_TIMEOUT_MS = 750
Const.NATIVE_BUMP_STALE_GRACE_MS = 750
Const.NATIVE_STALL_BACKOFF_MS = 5000
Const.ENGINE_PATH_FALLBACK_COOLDOWN_MS = 5000
Const.PATH_CONTINUOUS_RETARGET_DISTANCE = 0.22
Const.CLIENT_ZOMBIE_AGGRO_INDEX_MS = 250
Const.CLIENT_ZOMBIE_AGGRO_CELL_SIZE = 8
Const.CLIENT_ZOMBIE_AGGRO_TIER_MS = 50
Const.CLIENT_ZOMBIE_AGGRO_TIER_COUNT = 4
Const.VEHICLE_AVOIDANCE_CACHE_MS = 250
Const.VEHICLE_AVOIDANCE_CLEARANCE_TILES = 1
Const.VEHICLE_AVOIDANCE_FALLBACK_SCAN_RADIUS = 6
Const.VEHICLE_AVOIDANCE_MAX_SCAN_RADIUS = 24
PNC = PNC or {}
PNC.Const = PNC.Const or {}

local Const = PNC.Const
