"""Deterministic Lua output for Project Hoomans unique NPC definitions."""

from __future__ import annotations

import math
from numbers import Real
from pathlib import Path
from typing import Any, Iterable

from .schema import ConversionError, file_part, name_parts, normalize_definition


GENERATED_MARKER = "-- PNC_GENERATED_UNIQUE_NPC"
GENERATED_ID_MARKER = "-- uniqueDefinitionId: "
REGISTRAR_REQUIRE = "PNC/Generated/PNC_UniqueNPCRegistrar"
LOADER_NAME = "PNC_UniqueNPCDefinitions.lua"


class DefinitionExportError(ConversionError):
    """Raised when a normalized definition cannot be emitted as Lua."""


def _lua_string(value: str) -> str:
    output: list[str] = ['"']
    for character in str(value):
        code = ord(character)
        if character == "\\":
            output.append("\\\\")
        elif character == '"':
            output.append('\\"')
        elif character == "\n":
            output.append("\\n")
        elif character == "\r":
            output.append("\\r")
        elif character == "\t":
            output.append("\\t")
        elif code < 32 or code == 127:
            output.append(f"\\{code:03d}")
        else:
            output.append(character)
    output.append('"')
    return "".join(output)


def _is_array(value: dict[Any, Any]) -> bool:
    if not value:
        return False
    numeric: list[int] = []
    for key in value:
        if isinstance(key, int) and key >= 1:
            numeric.append(key)
        elif isinstance(key, str) and key.isdigit() and int(key) >= 1:
            numeric.append(int(key))
        else:
            return False
    return sorted(numeric) == list(range(1, len(numeric) + 1))


def _key_sort(key: Any) -> tuple[int, str]:
    if isinstance(key, int):
        return 0, f"{key:020d}"
    return 1, str(key)


def _lua_value(value: Any, level: int = 0) -> str:
    indent = "    " * level
    child_indent = "    " * (level + 1)
    if value is None:
        return "nil"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return _lua_string(value)
    if isinstance(value, Real) and not isinstance(value, bool):
        number = float(value)
        if not math.isfinite(number):
            raise DefinitionExportError("definition contains a non-finite number")
        if isinstance(value, int) or number.is_integer():
            return str(int(number))
        return format(number, ".15g")
    if isinstance(value, list):
        entries = [_lua_value(item, level + 1) for item in value]
        if not entries:
            return "{}"
        return "{\n" + ",\n".join(
            child_indent + entry for entry in entries
        ) + "\n" + indent + "}"
    if isinstance(value, dict):
        if _is_array(value):
            entries = [value.get(index, value.get(str(index))) for index in range(1, len(value) + 1)]
            return _lua_value(entries, level)
        entries = []
        for key in sorted(value, key=_key_sort):
            if not isinstance(key, (str, int, float)):
                raise DefinitionExportError(f"unsupported Lua table key: {key!r}")
            rendered_key = _lua_string(str(key))
            entries.append(
                f"{child_indent}[{rendered_key}] = {_lua_value(value[key], level + 1)}"
            )
        if not entries:
            return "{}"
        return "{\n" + ",\n".join(entries) + "\n" + indent + "}"
    raise DefinitionExportError(f"unsupported Lua value: {type(value).__name__}")


def module_stem(definition: dict[str, Any]) -> str:
    try:
        first, surname = name_parts(definition)
        return file_part(first) + file_part(surname)
    except ConversionError as exc:
        raise DefinitionExportError(str(exc)) from exc


def module_name(definition: dict[str, Any]) -> str:
    return module_stem(definition)


def export_definition_module(definition: dict[str, Any]) -> str:
    normalized = normalize_definition(definition)
    identifier = normalized["uniqueDefinitionId"]
    return (
        f"{GENERATED_MARKER}\n"
        f"{GENERATED_ID_MARKER}{identifier}\n"
        "-- Generated by tools/unique_npc_manager. Edit the Hoomans draft instead.\n"
        f'local register = require "{REGISTRAR_REQUIRE}"\n\n'
        "return register(\n"
        f"{_lua_value(normalized)}\n"
        ")\n"
    )


def _generated_module_paths(root: Path) -> Iterable[Path]:
    for path in sorted(root.glob("*.lua")):
        if path.name == LOADER_NAME:
            continue
        if ".bak." in path.name:
            continue
        try:
            content = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if GENERATED_MARKER in content:
            yield path


def rebuild_loader(root: Path) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    modules = [path.stem for path in _generated_module_paths(root)]
    lines = [
        "-- PNC_GENERATED_UNIQUE_NPC_LOADER",
        "-- Generated by tools/unique_npc_manager. Do not edit manually.",
        "",
    ]
    lines.extend(f'require "PNC/Generated/UniqueNPC/{name}"' for name in modules)
    lines.extend(["", "return true", ""])
    path = root / LOADER_NAME
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def generated_definition_id(path: Path) -> str | None:
    """Read the stable definition ID embedded in a generated module."""

    try:
        content = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    for line in content.splitlines():
        if line.startswith(GENERATED_ID_MARKER):
            value = line[len(GENERATED_ID_MARKER):].strip()
            return value or None
    # Modules generated before the marker was added can still be migrated by
    # reading the serialized ID from their register payload.
    marker = '["uniqueDefinitionId"] = "'
    start = content.find(marker)
    if start < 0:
        return None
    start += len(marker)
    end = content.find('"', start)
    return content[start:end] if end > start else None
