"""
discovery.py — Lua file discovery with path-pattern exclusions.

DEFAULT_EXCLUDE_PATTERNS covers auto-generated files produced by ModManager
(Manual pages, WhatsNew entries) that intentionally use patterns the linter
would flag.
"""
import fnmatch
import sys
from pathlib import Path
from typing import List, Optional

# Patterns matched against the full (resolved) file path.
# Shell-glob style, case-sensitive.  Add more with --exclude on the CLI.
DEFAULT_EXCLUDE_PATTERNS: List[str] = [
    "*/Manuals/*",       # ISManual definition files (auto-generated by ModManager)
    "*/WhatsNew/*",      # WhatsNew changelog files  (auto-generated by ModManager)
    "*/Deprecated/*",    # Archived/unused code
    "*/test/*",          # Test files (non-game)
    "*/tests/*",
]


def is_excluded(filepath: str, patterns: List[str]) -> bool:
    """Return True if *filepath* matches any glob pattern in *patterns*."""
    for pat in patterns:
        if fnmatch.fnmatch(filepath, pat):
            return True
    return False


def discover_files(
    paths: List[str],
    exclude_patterns: Optional[List[str]] = None,
) -> List[str]:
    """
    Expand paths (files or directories) into a sorted list of .lua files,
    filtering out any that match *exclude_patterns*.
    """
    if exclude_patterns is None:
        exclude_patterns = DEFAULT_EXCLUDE_PATTERNS

    files: List[str] = []
    for p in paths:
        path = Path(p).resolve()
        if path.is_file() and path.suffix == '.lua':
            candidates = [path]
        elif path.is_dir():
            candidates = sorted(path.rglob('*.lua'))
        else:
            print(f"Warning: {p!r} is not a .lua file or directory", file=sys.stderr)
            continue

        for f in candidates:
            fp = str(f)
            if not is_excluded(fp, exclude_patterns):
                files.append(fp)

    return files
