local Config = PNC.DirectorConfig

-- Population targets are soft demand signals. Hard limits always win over
-- user multipliers and remain intentionally outside SandboxVars.
Config.Population = {
    SECTOR_SIZE = 1000,
    ACTIVE_NEIGHBOR_RADIUS = 1,
    BASE_GROUPS_PER_ACTIVE_SECTOR = 5,
    BASE_SETTLEMENTS_PER_ACTIVE_SECTOR = 1.25,
    RELEVANT_SECTOR_FACTOR = 0.65,
    HEALTHY_LOWER_FACTOR = 0.80,
    FILL_UNTIL_FACTOR = 0.95,

    HARD_MAX_ABSTRACT_GROUPS = 256,
    HARD_MAX_SETTLEMENTS = 64,
    HARD_MAX_GROUPS_PER_SECTOR = 16,
    HARD_MAX_SETTLEMENTS_PER_SECTOR = 4,
    HARD_MAX_GENERATION_QUEUE = 64,
    HARD_MAX_GROUP_CREATIONS_PER_PUMP = 1,
    HARD_MAX_SETTLEMENT_CREATIONS_PER_PUMP = 1,
    HARD_MAX_NPC_RECORDS_PER_PUMP = 8,
    HARD_MAX_GROUP_CREATIONS_PER_HOUR = 2,
    -- A one-per-day global cap left the 3x3 player footprint visibly
    -- underfilled and repeatedly retried the same queued sector. Keep the
    -- per-pump cap at one, but allow the footprint to fill in three distinct
    -- sectors per world day.
    HARD_MAX_SETTLEMENT_CREATIONS_PER_DAY = 3,
    COMMITTED_GENERATION_HISTORY_LIMIT = 128,
    GENERATION_HISTORY_LIMIT = 96,
    DIRECTOR_LOG_HISTORY_LIMIT = 160,

    STARTER_META_SECTOR_BUDGET = 4,
    STARTER_META_CANDIDATE_LIMIT = 16,
    STARTER_META_INSPECTION_LIMIT = 256,
    STARTER_RETRY_HOURS = 1,
    STARTER_RUNTIME_RETRY_MS = 10000,
    STARTER_NPC_RECORD_BUDGET = 12,

    ACTIVE_SECTOR_REFRESH_HOURS = 15 / 60,
    GROUP_RECONCILE_HOURS = 2,
    SETTLEMENT_RECONCILE_HOURS = 12,
    GENERATION_QUEUE_HOURS = 15 / 60,
    INDEX_REPAIR_HOURS = 6,
    COMMUNITY_GROUP_RECONCILE_HOURS = 6,
    STARTUP_GRACE_HOURS = 30 / 60,
    BOOTSTRAP_RECONCILE_DELAY_HOURS = 15 / 60,
    INDEX_REPAIR_BUDGET = 16,
    RECONCILE_SECTOR_BUDGET = 4,
    CANDIDATE_EVALUATION_BUDGET = 5,

    QUEUE_EXPIRY_HOURS = 24,
    QUEUE_MAX_ATTEMPTS = 3,
    GROUP_INITIAL_COOLDOWN_HOURS = 3,
    GROUP_REGENERATION_COOLDOWN_HOURS = 24,
    SETTLEMENT_INITIAL_COOLDOWN_HOURS = 24,
    SETTLEMENT_REGENERATION_COOLDOWN_HOURS = 24 * 14,
    SITE_REGENERATION_COOLDOWN_HOURS = 24 * 21,
    RESERVATION_EXPIRY_HOURS = 2,

    PLAYER_EXCLUSION_RADIUS = 250,
    PLAYER_RESTRICTED_RADIUS = 500,
    PLAYER_PREFERRED_RADIUS = 900,
    SETTLEMENT_HARD_MIN_DISTANCE = 600,
    SETTLEMENT_PREFERRED_DISTANCE = 1200,

    GROUP_SIZE_MIN = 2,
    GROUP_SIZE_MAX = 4,
    SETTLEMENT_SIZE_MIN = 4,
    SETTLEMENT_SIZE_MAX = 7,
    COMMUNITY_GROUP_MIN_POPULATION = 5,
    COMMUNITY_GROUP_SIZE = 3,
    HARD_MAX_GROUPS_PER_COMMUNITY = 1,

    PLAYER_COUNT_EXPONENT = 0.45,
    PLAYER_COUNT_BONUS = 0.28,
    FOOTPRINT_BONUS = 0.12,

    DENSITY_MULTIPLIERS = {
        [1] = 0, [2] = 0.35, [3] = 0.65,
        [4] = 1.0, [5] = 1.35, [6] = 1.75,
    },
    RECOVERY_MULTIPLIERS = {
        [1] = 0, [2] = 0.35, [3] = 0.65,
        [4] = 1.0, [5] = 1.45, [6] = 2.0,
    },
    MULTIPLAYER_MULTIPLIERS = {
        [1] = 0, [2] = 0.65, [3] = 0.85,
        [4] = 1.0, [5] = 1.15, [6] = 1.30,
    },
    GROUP_ARCHETYPE_WEIGHTS = {
        REFUGEE = 0.28, LOOTER = 0.20,
        SCAVENGER = 0.30, WANDERER = 0.22,
    },
    GROUP_FACTION_ARCHETYPES = {
        REFUGEE = "refugee", LOOTER = "looter",
        SCAVENGER = "refugee", WANDERER = "refugee",
    },
    SETTLEMENT_FACTION_WEIGHTS = {
        settler = 0.55, trader = 0.18,
        refugee = 0.17, looter = 0.10,
    },
    SETTLEMENT_PREFERENCES = {
        settler = { HOUSE = 1.25, RURAL = 1.30,
            RESIDENTIAL = 1.15, COMMERCIAL = 0.75, INDUSTRIAL = 0.85 },
        trader = { COMMERCIAL = 1.35, ROAD = 1.25,
            INDUSTRIAL = 1.05, HOUSE = 0.85 },
        refugee = { HOUSE = 1.20, RURAL = 1.15,
            SAFE = 1.25, COMMERCIAL = 0.75 },
        looter = { COMMERCIAL = 1.25, INDUSTRIAL = 1.25,
            WAREHOUSE = 1.35, ROAD = 1.10 },
    },
}
