-- Stable colony-storage production provider entry point.

if PsychopatzCore and PsychopatzCore.RuntimeRole
    and not PsychopatzCore.RuntimeRole.AllowsServerCode() then return end

require "PNC/Colony/Storage/ColonyStorageService/ColonyStorageService_Production/PNC_ColonyStorageService_Production_Core"
require "PNC/Colony/Storage/ColonyStorageService/ColonyStorageService_Production/PNC_ColonyStorageService_Production_Reservations"
require "PNC/Colony/Storage/ColonyStorageService/ColonyStorageService_Production/PNC_ColonyStorageService_Production_Transactions"
require "PNC/Colony/Storage/ColonyStorageService/ColonyStorageService_Production/PNC_ColonyStorageService_Production_Transfers"
require "PNC/Colony/Storage/ColonyStorageService/ColonyStorageService_Production/PNC_ColonyStorageService_Production_Queries"

return PNC.ColonyStorageService
