-- Data-only objective conduct mappings for accepted social events.

PNC = PNC or {}
PNC.ConductDefinitions = {
    treated_wound = {
        role = "caregiver",
        participants = "actor",
        effects = { compassion = 2, generosity = 1 },
        decayPerDay = 0.02,
        visibility = "direct",
        shareable = false,
        tags = { treatment = true, help = true },
    },
    saved_from_incapacitation = {
        role = "rescuer",
        participants = "actor",
        effects = {
            compassion = 8, courage = 5,
            groupLoyalty = 4, reliability = 3,
        },
        decayPerDay = 0.0025,
        visibility = "direct",
        shareable = true,
        tags = { rescue = true, help = true, life_saving = true },
    },
    protected_from_attacker = {
        role = "protector",
        participants = "actor",
        effects = {
            courage = 6, groupLoyalty = 3, reliability = 2,
        },
        decayPerDay = 0.0075,
        visibility = "direct",
        shareable = true,
        tags = { protection = true, combat = true },
    },
    witnessed_player_kill = {
        role = "combatant",
        participants = "actor",
        effects = { courage = 3, reliability = 1 },
        decayPerDay = 0.02,
        visibility = "direct",
        shareable = true,
        tags = { combat = true, witnessed = true },
    },
    witnessed_player_hurt = {
        role = "combatant",
        participants = "actor",
        effects = { courage = -1, reliability = -1 },
        decayPerDay = 0.03,
        visibility = "direct",
        shareable = true,
        tags = { combat = true, witnessed = true, vulnerability = true },
    },
    player_damaged_npc = {
        role = "antagonist",
        participants = "actor",
        effects = { restraint = -3, compassion = -2 },
        decayPerDay = 0.025,
        visibility = "direct",
        shareable = true,
        tags = { combat = true, hostility = true },
    },
    faction_member_attacked = {
        role = "antagonist",
        participants = "actor",
        required = false,
        -- The direct victim event already records the player's conduct. The
        -- faction fan-out must not multiply that conduct penalty per member.
        effects = {},
        decayPerDay = 0.025,
        visibility = "public",
        shareable = false,
        tags = { combat = true, faction = true, hostility = true },
    },
    survived_combat_together = {
        role = "participant",
        participants = "actor_and_target",
        effects = {
            reliability = 2, courage = 2, groupLoyalty = 1,
        },
        decayPerDay = 0.015,
        visibility = "direct",
        shareable = false,
        tags = { combat = true, teamwork = true, shared_danger = true },
    },
    abandoned_in_combat = {
        role = "abandoner",
        participants = "actor",
        effects = {
            reliability = -8, courage = -6,
            groupLoyalty = -8, compassion = -3,
        },
        decayPerDay = 0.003,
        visibility = "direct",
        shareable = true,
        tags = { abandonment = true, betrayal = true, combat = true },
    },
    player_emote_insult = {
        role = "antagonist",
        participants = "actor",
        effects = { restraint = -2, compassion = -2 },
        decayPerDay = 0.05,
        visibility = "direct",
        shareable = false,
        tags = { hostile = true, emote = true, abuse = true },
    },
    player_emote_thumbsdown = {
        role = "disapprover",
        participants = "actor",
        effects = { restraint = -1 },
        decayPerDay = 0.08,
        visibility = "direct",
        shareable = false,
        tags = { hostile = true, emote = true, disapproval = true },
    },
    player_emote_wavehi = {
        role = "greeter",
        participants = "actor",
        effects = { restraint = 1 },
        decayPerDay = 0.08,
        visibility = "direct",
        shareable = false,
        tags = { greeting = true, emote = true },
    },
    player_emote_wavebye = {
        role = "greeter",
        participants = "actor",
        effects = { restraint = 1 },
        decayPerDay = 0.10,
        visibility = "direct",
        shareable = false,
        tags = { farewell = true, emote = true },
    },
    player_emote_thankyou = {
        role = "grateful",
        participants = "actor",
        effects = { compassion = 1, restraint = 1 },
        decayPerDay = 0.05,
        visibility = "direct",
        shareable = false,
        tags = { gratitude = true, emote = true },
    },
    player_emote_thumbsup = {
        role = "encourager",
        participants = "actor",
        effects = { groupLoyalty = 1 },
        decayPerDay = 0.05,
        visibility = "direct",
        shareable = false,
        tags = { praise = true, emote = true },
    },
    player_emote_clap = {
        role = "encourager",
        participants = "actor",
        effects = { groupLoyalty = 1 },
        decayPerDay = 0.05,
        visibility = "direct",
        shareable = false,
        tags = { praise = true, emote = true },
    },
    player_emote_salute = {
        role = "respectful",
        participants = "actor",
        effects = { restraint = 1 },
        decayPerDay = 0.05,
        visibility = "direct",
        shareable = false,
        tags = { respect = true, emote = true },
    },
}

return PNC.ConductDefinitions
